jenkinsdata:
  build: jenkins-data

jenkinsmaster:
  build: jenkins-master
  volumes_from:
    - jenkinsdata
  ports:
    - "50000:50000"

jenkinsnginx:
  build: jenkins-nginx
  ports:
    - "80:80"
  links:
    # jenkinsmaster is defined above
    # jenkins-master is the named link, the same as in jenkins.conf
    - jenkinsmaster:jenkins-master